'use strict';

module.exports = {
  html: {
    showAllWaterfallSummary: false,
    pageSummaryMetrics: [
      'transferSize.total',
      'requests.total',
      'thirdParty.requests',
      'transferSize.javascript',
      'transferSize.css',
      'transferSize.image',
      'score.performance'
    ],
    summaryBoxes: [
      'score.score',
      'score.accessibility',
      'score.bestpractice',
      'score.privacy',
      'score.performance',
      'timings.firstPaint',
      'timings.firstContentfulPaint',
      'timings.fullyLoaded',
      'timings.pageLoadTime',
      'timings.largestContentfulPaint',
      'timings.FirstVisualChange',
      'timings.LastVisualChange',
      'timings.SpeedIndex',
      'timings.PerceptualSpeedIndex',
      'timings.VisualReadiness',
      'timings.VisualComplete',
      'timings.backEndTime',
      'googleWebVitals.cumulativeLayoutShift',
      'requests.total',
      'requests.javascript',
      'requests.css',
      'requests.image',
      'transferSize.total',
      'transferSize.html',
      'transferSize.javascript',
      'contentSize.javascript',
      'transferSize.css',
      'transferSize.image',
      'thirdParty.transferSize',
      'thirdParty.requests',
      'webpagetest.SpeedIndex',
      'webpagetest.lastVisualChange',
      'webpagetest.render',
      'webpagetest.visualComplete',
      'webpagetest.visualComplete95',
      'webpagetest.TTFB',
      'webpagetest.fullyLoaded',
      'axe.critical',
      'axe.serious',
      'axe.minor',
      'axe.moderate',
      'cpu.longTasksTotalDuration',
      'cpu.longTasks',
      'cpu.totalBlockingTime',
      'cpu.maxPotentialFid',
      'sustainable.totalCO2',
      'sustainable.co2PerPageView',
      'sustainable.co2FirstParty',
      'sustainable.co2ThirdParty'
    ]
  }
};
