version: '2'
services:
    sitespeed:
        build: ../
        command: -V
        volumes:
            - ./sitespeed-result/:/sitespeed.io/sitespeed-result
        shm_size: 1g
#    caddy:
#        image: abiosoft/caddy
#        ports:
#            - "2015:2015"
#        volumes:
#            - ./sitespeed-result/:/srv
    grafana:
        image: grafana/grafana:4.2.0
        links:
            - graphite
            - influxdb
        ports:
            - "3000:3000"
        volumes:
            - grafana:/var/lib/grafana
    grafana-setup:
        build: ./grafana-setup
        links:
            - grafana
    graphite:
        image: sitespeedio/graphite
    influxdb:
        image: influxdb:1.2.2
        ports:
           - "8086:8086"
           - "8083:8083"
volumes:
    grafana:
