FROM node:24.11.0-trixie-slim

ARG TARGETPLATFORM=linux/amd64

ENV SITESPEED_IO_BROWSERTIME__DOCKER=true
ENV SITESPEED_IO_BROWSERTIME__VIDEO=false
ENV SITESPEED_IO_BROWSERTIME__BROWSER=firefox
ENV SITESPEED_IO_BROWSERTIME__VISUAL_METRICS=false
ENV SITESPEED_IO_BROWSERTIME__HEADLESS=true

RUN apt-get update && \
    apt-get install -y --no-install-recommends --no-install-suggests \
        wget ca-certificates && \
    install -d -m 0755 /etc/apt/keyrings && \
    wget -qO /etc/apt/keyrings/packages.mozilla.org.asc https://packages.mozilla.org/apt/repo-signing-key.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main" > /etc/apt/sources.list.d/mozilla.list && \
    printf 'Package: *\nPin: origin packages.mozilla.org\nPin-Priority: 1000\n' > /etc/apt/preferences.d/mozilla && \
    apt-get update && \
    apt-get install -y --no-install-recommends --no-install-suggests \
        firefox tcpdump iproute2 sudo && \
    apt-get purge -y --auto-remove wget && \
    rm -rf /var/lib/apt/lists/* /tmp/*

# Install sitespeed.io
WORKDIR /usr/src/app
COPY . /usr/src/app
RUN CHROMEDRIVER_SKIP_DOWNLOAD=true EDGEDRIVER_SKIP_DOWNLOAD=true \
    npm ci --omit=dev --omit=optional && \
    npm cache clean --force && \
    rm -fR /usr/src/app/node_modules/selenium-webdriver/bin

COPY docker/scripts/start-slim.sh /start.sh

# Allow all users to run commands needed by sitespeedio/throttle via sudo
# See https://github.com/sitespeedio/throttle/blob/main/lib/tc.js
RUN echo 'ALL ALL=NOPASSWD: /usr/sbin/tc, /usr/sbin/route, /usr/sbin/ip' > /etc/sudoers.d/tc

ENTRYPOINT ["/start.sh"]
VOLUME /sitespeed.io
WORKDIR /sitespeed.io
