version: '2'
services:
    grafana:
        image: grafana/grafana
        depends_on:
            - graphite
        links:
            - graphite
        ports:
            - "3000:3000"
    graphite:
        image: sitespeedio/graphite
        ports:
            - "2003:2003"
            - "8080:80"
