permalink: /:title/
baseurl: 
markdown: kramdown
compress_html:
  clippings: all
  endings: all
include: ["_headers"]
kramdown:
    enable_coderay: false
    coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style
gems:

