permalink: /:title/
baseurl: 
markdown: kramdown
compress_html:
  clippings: all
  endings: all
include: ["_headers"]
highlighter: none
kramdown:
  syntax_highlighter_opts:
      disable : true
gems:

