export function addOptions(yargs) {
  yargs
    .option('browsertime.safari.ios', {
      alias: 'safari.ios',
      default: false,
      describe:
        'Use Safari on iOS. You need to choose browser Safari and iOS to run on iOS. Only works on OS X Catalina and iOS 13 (and later).',
      type: 'boolean',
      group: 'Safari'
    })
    .option('browsertime.safari.deviceName', {
      alias: 'safari.deviceName',
      describe:
        'Set the device name. Device names for connected devices are shown in iTunes.',
      group: 'Safari'
    })
    .option('browsertime.safari.deviceUDID', {
      alias: 'safari.deviceUDID',
      describe:
        'Set the device UDID. If Xcode is installed, UDIDs for connected devices are available via the output of "xcrun simctl list devices" and in the Device and Simulators window (accessed in Xcode via "Window > Devices and Simulators")',
      group: 'Safari'
    })
    .option('browsertime.safari.deviceType', {
      alias: 'safari.deviceType',
      describe:
        'Set the device type. If the value of safari:deviceType is `iPhone`, safaridriver will only create a session using an iPhone device or iPhone simulator. If the value of safari:deviceType is `iPad`, safaridriver will only create a session using an iPad device or iPad simulator.',
      group: 'Safari'
    })
    .option('browsertime.safari.useTechnologyPreview', {
      alias: 'safari.useTechnologyPreview',
      type: 'boolean',
      default: false,
      describe: 'Use Safari Technology Preview',
      group: 'Safari'
    })
    .option('browsertime.safari.diagnose', {
      alias: 'safari.diagnose',
      describe:
        'When filing a bug report against safaridriver, it is highly recommended that you capture and include diagnostics generated by safaridriver. Diagnostic files are saved to ~/Library/Logs/com.apple.WebDriver/',
      group: 'Safari'
    })
    .option('browsertime.safari.useSimulator', {
      alias: 'safari.useSimulator',
      describe:
        'If the value of useSimulator is true, safaridriver will only use iOS Simulator hosts. If the value of safari:useSimulator is false, safaridriver will not use iOS Simulator hosts. NOTE: An Xcode installation is required in order to run WebDriver tests on iOS Simulator hosts.',
      default: false,
      type: 'boolean',
      group: 'Safari'
    });
}
