name: Build autobuild container that runs tests on dashboard.sitespeed.io
on:
  push:
    branches:
    - main
jobs:
  docker:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'docs:') }}
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push sitespeed.io
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          push: true
          provenance: false
          tags: sitespeedio/sitespeed.io-autobuild:main