name: Run unit tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: google-chrome --version
    - run: firefox --version
    - name: Run unit tests
      uses: GabrielBB/xvfb-action@v1.2
      with:
        run: npm test
