name: Run browser test Safari
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: sudo safaridriver --enable
    - run: npm ci
    - run: bin/sitespeed.js -b safari https://www.sitespeed.io/
