name: OSX Safari
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies 
      run: |
        sudo safaridriver --enable 
        npm ci
    - name: Run test
      run: bin/sitespeed.js -b safari https://www.sitespeed.io/
