name: OSX Safari
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: macos-15
    if: ${{ !contains(github.event.head_commit.message, 'docs:') }}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
      with:
        egress-policy: audit
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - name: Use Node.js
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
      with:
        node-version: '22.x'
        cache: 'npm'
    - name: Install dependencies
      run: |
        sudo safaridriver --enable 
        npm ci
    - name: Install local HTTP server
      run: npm install serve -g
    - name: Start local HTTP server
      run: (serve test/data/html/ -l 3001&)
    - name: Run test
      run: bin/sitespeed.js -b safari http://127.0.0.1:3001/
    - name: Run Safari test with config
      run: node bin/sitespeed.js -b safari --config test/exampleConfig.json http://127.0.0.1:3001/
