name: sitespeed.io action example
on:
  push:
    branches:
    - main
jobs:
  run-sitespeed:
    runs-on: ubuntu-latest
    name: running sitespeed.io
    steps:
      - name: code checkout
        uses: actions/checkout@v3
      # Here we build our own container to make sure we test against our latest code
      # but YOU can just used the latest version by specifying 
      # sitespeedio/sitespeed.io:VERSION
      - name: Build Docker containers
        run: |
          docker buildx install
          docker buildx build --load --platform linux/amd64 -t sitespeedio/sitespeed.io .
      - name: running sitespeed.io container with arguments and optional Docker options
        run: docker run -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io https://www.sitespeed.io --budget.configPath .github/budget.json -n 1 