name: Windows Edge
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: windows-latest
    if: ${{ !contains(github.event.head_commit.message, 'docs:') }}
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install sitespeed.io
      run: npm ci
      env:
        CHROMEDRIVER_SKIP_DOWNLOAD: true
        GECKODRIVER_SKIP_DOWNLOAD: true
    - run: choco outdated
    - name: Show versions
      run: powershell "Get-AppxPackage -Name *MicrosoftEdge.* | Foreach Version"
      shell: cmd
    #- name: Install dependencies
    #  run: choco install microsoft-edge
    - name: Run Edge test
      run: node bin/sitespeed.js -b edge https://www.sitespeed.io/
      shell: cmd
    - name: Run Edge test with scripting
      run: node bin/sitespeed.js -b edge --multi test/prepostscripts/multiWindows.cjs -n 1
      shell: cmd
    - name: Run Edge test with config
      run: node bin/sitespeed.js -b edge --config test/exampleConfig.json https://www.sitespeed.io/
      shell: cmd
    