name: Example to run sitespeed.io on Windows
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: windows-2025
    if: ${{ !contains(github.event.head_commit.message, 'docs:') }}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
      with:
        egress-policy: audit
    - name: Use Node.js
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
      with:
        node-version: '22.x'
    - name: Install sitespeed.io
      run: npm install sitespeed.io -g
      shell: bash
    # ffmpeg, Python, and Chrome are preinstalled on the windows-2025 runner image
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install pyssim OpenCV-Python Numpy scipy
      shell: cmd
    - name: Example running test on Windows
      run: sitespeed.io -n 1 --video --visualMetrics --viewPort 1024x768 https://www.sitespeed.io/ 
      shell: bash