name: Windows Edge
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: windows-2025
    if: ${{ !contains(github.event.head_commit.message, 'docs:') }}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
      with:
        egress-policy: audit
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - name: Use Node.js
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
      with:
        node-version: '20.x'
        cache: 'npm'
    - name: Install sitespeed.io
      run: npm ci
      env:
        CHROMEDRIVER_SKIP_DOWNLOAD: true
        GECKODRIVER_SKIP_DOWNLOAD: true
    - name: Show versions
      run: powershell "Get-AppxPackage -Name *MicrosoftEdge.* | Foreach Version"
      shell: cmd
    #- name: Install dependencies
    #  run: choco install microsoft-edge
    - name: Run Edge test
      run: node bin/sitespeed.js -b edge https://www.sitespeed.io/
      shell: cmd
    - name: Run Edge test with scripting
      run: node bin/sitespeed.js -b edge --multi test/prepostscripts/multiWindows.cjs -n 1
      shell: cmd
    - name: Run Edge test with config
      run: node bin/sitespeed.js -b edge --config test/exampleConfig.json https://www.sitespeed.io/
      shell: cmd
    