name: Run browser test Windows
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: GECKODRIVER_SKIP_DOWNLOAD=true CHROMEDRIVER_SKIP_DOWNLOAD=true npm ci
    - name: Run Edge test
      run: node bin/sitespeed.js -b edge https://www.sitespeed.io/ 
      shell: cmd
      
